# Generated by Django 3.0.2 on 2020-02-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='static/images/default_img.jpg', upload_to='static/images'),
        ),
    ]
