# Generated by Django 3.0.2 on 2020-02-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200205_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='images/default_img.jpg', upload_to='images'),
        ),
    ]
