# Generated by Django 3.0.4 on 2020-04-22 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20200422_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='price',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='price',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
