# Generated by Django 3.0.4 on 2020-04-28 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_auto_20200427_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'default_related_name': 'prices'},
        ),
    ]
