# Generated by Django 3.0.4 on 2020-04-28 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20200428_1159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'default_related_name': 'prices', 'ordering': ['date']},
        ),
    ]
